language: node_js

node_js:
  - '6'

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.yarn-cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install: yarn

after_success: yarn lint

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
